#code to rename audio clips so identitiy is unknown- renames and saves copy to a new directory

rm(list=ls())

# READ in directory of audio files...
inDir =    "F:\\RESEARCH\\NSNSD_EclipseSoundScape\\AUDIO_eclipse\\"
copy2dir = "F:\\RESEARCH\\NSNSD_EclipseSoundScape\\AUDIO_eclipse\\SurveyClips"
setwd(inDir)
wavFiles <- dir(pattern=".wav$")

# READ in previously created spreadsheet clip names generated by 
# <Eclipse_FileNames.R> and then random assignment of survey and clip id
clipNames = read.csv( paste(copy2dir, '\\EclipseSoundscape_clips.csv', sep ="") )


for (ff in 1:length(wavFiles)  ) { #for testing: ff = 20
  
  #find the matching column
  mtch = clipNames[clipNames$FileNames == wavFiles[ff],]
  
  if (is.na(mtch$ClipID) == FALSE ) {
    
    #get new name
    newName = paste('Surv', mtch$SurveyNumber, '_ClipID', mtch$ClipID, ".wav",sep="")
    
    #copy file to new directory
    filestocopy = wavFiles[ff]
    file.copy(from=filestocopy, to=copy2dir, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE)
    
    #rename file in new directory
    setwd(copy2dir)
    file.rename ( wavFiles[ff], newName )
    
    #reset to the in directory...
    setwd(inDir)
    
  }
}
