# code to batch re-name files by matching them with their previous names
# practicing on a dummy directory so i don't eff up my wav files

rm(list=ls())

inDir =    "/Users/Marina/Documents/dummy/test/files/"
copy2dir = "/Users/Marina/Documents/dummy/test/renamed_files/"
wavFiles <- dir(path = inDir, pattern=".png$")

# READ in previously created spreadsheet clip names generated by 
# <Eclipse_FileNames.R> and then random assignment of survey and clip id
clipNames = read.csv("/Users/Marina/Documents/dummy/test/dummy_filenames.csv")
clipNames$old_file <- paste(clipNames$old_file, ".png", sep = "")

#I'm good up to here, I just don't understand this for loop--

for (ff in 1:length(wavFiles)  ) { #for testing: ff = 20
  
  #find the matching column
  mtch = clipNames[clipNames$old_file == wavFiles[ff],] # why is this new file? shouldnt it be old?
  
  #if (is.na(mtch$ClipID) == FALSE ) {
    
    #get new name
    newName = paste('Surv_ClipID_', mtch$new_file, ".wav", sep="")
    
    #copy file to new directory
    filestocopy = wavFiles[ff]
    file.copy(from = paste(inDir, filestocopy, sep = ""), to=copy2dir, overwrite = TRUE, recursive = FALSE, copy.mode = TRUE)
    #rename file in new directory
    setwd(copy2dir)
    file.rename(wavFiles[ff], newName)
    
    #reset to the in directory...
    setwd(inDir)
    
#  }
}

